181510

name: TWOJA NAZWA

tagline: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Image_URL: assets/images/avatar.jpg

Cover_Image: assets/images/background.jpg

links:

  - Name: Facebook
    URL: https://www.facebook.com
    Username: nazwaprofilu
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

  - Name: Instagram
    URL: https://www.instagram.com
    Username: nazwaprofilu
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

  - Name: Twitter
    URL: https://twitter.com
    Username: nazwaprofilu
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: nazwakalu
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

  - Name: Email
    URL: 'mailto:adres@email.pl'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

  - Name: Messenger
    URL: https://m.me
    Username: nazwaprofilu
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

  - Name: Telegram
    URL: http://telegram.me
    Username: nazwaprofilu
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

  - Name: TikTok
    URL: https://www.tiktok.com
    Username: nazwaprofilu
    Color: '#FE2C55'
    Icon-Class: fab fa-tiktok

  - Name: INNY LINK
    URL: https://twojlink.pl
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'


footer: 'Yes'

compress_html:
  clippings: all

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

markdown: kramdown
