# YOUR NAME OR TITLE OF YOUR SITE
name: Flying_4Free

# YOUR BRAND/PERSONAL TAGLINE
tagline: '<p><span>hello</span><span>How are you</span></p>'

# YOUR/BRAND IMAGE URL
Image_URL: https://cdn4.iconfinder.com/data/icons/bold-circular-app-web-icons/1153/circle_user_bold-512.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: assets/images/background.jpg

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: flying_4free
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: flying_4free
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
